### ISSUE TITLE
Index out of bounds if first failing nightly is the most recent.

### ISSUE THREAD

**Issue by kamalmarhubi** [kamalmarhubi/rust-bisect#8]
```
$ env RUST_BACKTRACE=1 ~/projects/rust-bisect/target/debug/rust-bisect
--good nightly-2016-10-28 --bad nightly-2016-11-02 -- cargo build
finding available nightlies between nightly-2016-10-28 and nightly-2016-11-02
bisecting across 1 nightlies (about 0 steps)
testing with nightly-2016-10-28
using existing install for 'nightly-2016-10-28'
   Compiling nom v1.2.4
   Compiling semver v0.1.20
   Compiling libc v0.2.17
   Compiling byteorder v0.5.3
   Compiling rustc_version v0.1.7
   Compiling procinfo v0.2.3 (file:///home/kamal/clones/procinfo-rs)
warning: unused or unknown feature, #[warn(unused_features)] on by default
 --> src/lib.rs:2:36
  |
2 | #![cfg_attr(rustc_nightly, feature(test))]
  |                                    ^^^^

    Finished debug [unoptimized + debuginfo] target(s) in 57.32 secs
command succeeded with nightly-2016-10-28
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', ../src/libcol
lections/vec.rs:1382
stack backtrace:
   1:     0x561854df7058 - std::sys::imp::backtrace::tracing::imp::write::he3d1bfbdbf113480
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/.
./src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x561854dfec9f - std::panicking::default_hook::{{closure}}::h575f1b40d2e88f07
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/.
./src/libstd/panicking.rs:247
   3:     0x561854dfd206 - std::panicking::default_hook::h3d5dccce8125d0cf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/.
./src/libstd/panicking.rs:263
   4:     0x561854dfd857 - std::panicking::rust_panic_with_hook::h00b81bb3dcbd51f2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/.
./src/libstd/panicking.rs:451
   5:     0x561854dfd6e4 - std::panicking::begin_panic::ha6a0d553db9869ff
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/.
./src/libstd/panicking.rs:413
   6:     0x561854dfd609 - std::panicking::begin_panic_fmt::h24d113aee3ee4081
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/.
./src/libstd/panicking.rs:397
   7:     0x561854dfd597 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/.
./src/libstd/panicking.rs:373
   8:     0x561854e346ad - core::panicking::panic_fmt::he441b2ea2036b98a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/.
./src/libcore/panicking.rs:69
   9:     0x561854e34658 - core::panicking::panic_bounds_check::h344fb76ff622c3e5
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/.
./src/libcore/panicking.rs:56
  10:     0x561854a56055 - <collections::vec::Vec<T> as core::ops::Index<usize>>::index::h3612f
73c7dbcd317
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/.
./src/libcollections/vec.rs:1382
  11:     0x561854a5c8a4 - rust_bisect::run::h4c1d3aaaec88bc97
                        at /home/kamal/projects/rust-bisect/src/lib.rs:137
  12:     0x561854a4097f - rust_bisect::main::run::hb52ac96d165323e3
                        at /home/kamal/projects/rust-bisect/src/main.rs:24
  13:     0x561854a40380 - rust_bisect::main::hf008915c47a09e14
                        at /home/kamal/projects/rust-bisect/src/main.rs:27
  14:     0x561854e0677a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/.
./src/libpanic_unwind/lib.rs:97
  15:     0x561854dfdf8a - std::rt::lang_start::h74b3afbdd8daef1c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/.
./src/libstd/panicking.rs:332
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/.
./src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/.
./src/libstd/rt.rs:57
  16:     0x561854a40c23 - main
  17:     0x7f33b145c2b0 - __libc_start_main
  18:     0x561854a3ad69 - _start
  19:                0x0 - <unknown>
```

**Comment by kamalmarhubi** [comment]
Need to see why only `2016-10-28` was included.
